# Generated by Django 5.0.7 on 2024-08-12 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.category'),
        ),
    ]
