# Generated by Django 5.0.7 on 2024-08-02 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='voice_recordings/'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
